---
title: "Tarea-3-estadistica-inferencial"
author: "Equipo-2"
date: "2024-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library ( ggpattern )
library ( ggplot2 )
library ( ggpubr )

 # Valores conocidos .
 n <- 100

 # Valores supuestos por Lola .
 media_nula <- 10
 sigma <- 1


 # Calcular el error est á ndar .
 SE <- sigma / sqrt ( n )

 # Gr á ficar la distribuci ó n muestral de las medias si la hip ó tesis
 # nula fuera verdadera .

 # Primero , el gr á fico base
 g_x_limites <- media_nula + c( -0.001 , 5.00) * SE
 g <- ggplot () + xlim ( g_x_limites )
 g <- g + labs ( x = "Tiempo de ejecución [s]" , y = "Densidad")
 g <- g + labs ( title = " Distribución muestral de las medias" )
 g <- g + theme_pubr ()
 
 # Agregamos la hip ó tesis nula
 dist_0 <- stat_function ( fun = dnorm ,
 args = list ( mean = media_nula , sd = SE ) ,
 geom = "area",
 colour = " red ", fill = " red ", alpha = 0.1)
 g1 <- g + dist_0
 g1 <- g1 + geom_vline ( xintercept = media_nula , colour = " red ")

 # Calcular las regiones cr í ticas de la hip ó tesis nula .
 z_critico_superior <- 10.25

 # Colorear regiones de rechazo en el gr á fico y el valor nulo .

 g2 <- g1 + stat_function ( fun = dnorm ,
 args = list ( mean = media_nula , sd = SE ) ,
 geom = "area",
 xlim = c( z_critico_superior , g_x_limites [2]) ,
 fill = " red ", alpha = 0.6)
 print ( g2 )
```
## Se puede observar que la significancia es aproximadamente de 0.05
```{r}
x <- seq(7, 13, length=100)
y <- dnorm(x, mean=10, sd=1)
plot(x, y)
```
```{r}
library(pwr)
d <- (µ−µ0)/σ

pwr.norm.test(d,100,0.05,0.75,"greater")
```

